services:
  # Backend API Service
  - type: web
    name: dealdrop-backend
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: ORIGIN
        fromService:
          type: web
          name: dealdrop-frontend
          property: url
      - key: RESEND_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

  # Frontend Static Site
  - type: web
    name: dealdrop-frontend
    runtime: static
    region: oregon
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API
        fromService:
          type: web
          name: dealdrop-backend
          property: url
      - key: VITE_AUCTION_API
        fromService:
          type: web
          name: dealdrop-backend
          envVarKey: url

# Database (Note: Render doesn't provide free MongoDB, use MongoDB Atlas)
# Add MongoDB Atlas connection string to MONGO_URI environment variable
