services:
  # Backend API Service
  - type: web
    name: dealdrop-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: ORIGIN
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

  # Frontend Static Site
  - type: web
    name: dealdrop-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API
        sync: false
      - key: VITE_AUCTION_API
        sync: false

# Note: 
# 1. Use MongoDB Atlas for database (Render doesn't provide free MongoDB)
# 2. After deploying backend, update ORIGIN in backend settings with frontend URL
# 3. After deploying backend, update VITE_API and VITE_AUCTION_API in frontend settings with backend URL
